version: '3'

services:
  nighttab:
    build:
      context: .
    ports:
      - "8888:80"    # Port für den Webzugriff auf nightTab
      - "3100:3100"  # Neuer Port für die API
    volumes:
      - ./data:/app/data  # Volume für persistente Einstellungen
