version: '3'

services:
  nighttab:
    build:
      context: .
    ports:
      - "8888:80"    # Port für den Webzugriff auf nightTab
      - "3000:3000"  # Port für die interne API
    volumes:
      - ./data:/app/data  # Volume für persistente Einstellungen
